"""first migrate

Revision ID: 4353e46ae68e
Revises: 
Create Date: 2021-10-30 00:54:14.762360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4353e46ae68e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('long', sa.String(), nullable=True),
    sa.Column('short', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urls')
    # ### end Alembic commands ###
